"""Remote data asset registry (auto-generated by data_registry.py).

Do not edit manually.  Re-run ``scripts/data_registry.py generate``
to update after uploading new data.

Production Zenodo record: https://zenodo.org/records/19549668
"""

DATA_DIR_NAME = "nichenetr_data"
CACHE_DIR_NAME = "nichenetr_py"

REGISTRY: dict[str, dict[str, str]] = {
    "gr_network_human.parquet": {
        "url": "https://zenodo.org/records/19549668/files/gr_network_human.parquet?download=1",
        "sha256": "2bede140181c738cbf43c991d4fa1ec1a22383fbfabe3847219121994555fbe3",
    },
    "hnscc_expression.npz": {
        "url": "https://zenodo.org/records/19549668/files/hnscc_expression.npz?download=1",
        "sha256": "f6ad4a32df1ff12b54eac43452909cb7448d0ec23bd44b5c520daf1adca2471f",
    },
    "hnscc_expression_colnames.json": {
        "url": "https://zenodo.org/records/19549668/files/hnscc_expression_colnames.json?download=1",
        "sha256": "24c38f1811382218474a972304ab8e3d5792e2557309b4173a754edc518ba30b",
    },
    "hnscc_expression_rownames.json": {
        "url": "https://zenodo.org/records/19549668/files/hnscc_expression_rownames.json?download=1",
        "sha256": "61c33375ff18431460ac31d412e2bb32bd437387128a2b94176c8caf46eb5160",
    },
    "hnscc_sample_info.parquet": {
        "url": "https://zenodo.org/records/19549668/files/hnscc_sample_info.parquet?download=1",
        "sha256": "fc33e2dd7c69aa7b3c0aedbc1c5609515cba3eeb20912a87b0252acfdbb9f3c5",
    },
    "ligand_target_matrix_human.npz": {
        "url": "https://zenodo.org/records/19549668/files/ligand_target_matrix_human.npz?download=1",
        "sha256": "813851f6ce29fb996db9fb73393263d743c558dc976021bb16947aa650a44a24",
    },
    "ligand_target_matrix_human_colnames.json": {
        "url": "https://zenodo.org/records/19549668/files/ligand_target_matrix_human_colnames.json?download=1",
        "sha256": "63fefd3d7fd7edbf8829b2378c767566bf8c38dca5f1a76df74a06396c76648e",
    },
    "ligand_target_matrix_human_rownames.json": {
        "url": "https://zenodo.org/records/19549668/files/ligand_target_matrix_human_rownames.json?download=1",
        "sha256": "970c93c1fedeb1298b0b287ac0a03d7eb792302218ed307c511d2f03928ccd4f",
    },
    "ligand_target_matrix_mouse.npz": {
        "url": "https://zenodo.org/records/19549668/files/ligand_target_matrix_mouse.npz?download=1",
        "sha256": "cf5c878bac2698abf7a6f213eb264e94fcc0694acc9b596c8e635f813aae89e6",
    },
    "ligand_target_matrix_mouse_colnames.json": {
        "url": "https://zenodo.org/records/19549668/files/ligand_target_matrix_mouse_colnames.json?download=1",
        "sha256": "0088e39d87702bafab8c6fc524aa3ae596c83f4c9cffaa3bfce285faef2e6424",
    },
    "ligand_target_matrix_mouse_rownames.json": {
        "url": "https://zenodo.org/records/19549668/files/ligand_target_matrix_mouse_rownames.json?download=1",
        "sha256": "31052a58cf051f7cde36436c04c30904b9113d90ea7f21360c9aa94e710d85c7",
    },
    "ligand_tf_matrix.npz": {
        "url": "https://zenodo.org/records/19549668/files/ligand_tf_matrix.npz?download=1",
        "sha256": "6bab299fa6093548274e5bebede3659ecffb09b20ae04fa011012f50f7e7a107",
    },
    "ligand_tf_matrix_colnames.json": {
        "url": "https://zenodo.org/records/19549668/files/ligand_tf_matrix_colnames.json?download=1",
        "sha256": "63fefd3d7fd7edbf8829b2378c767566bf8c38dca5f1a76df74a06396c76648e",
    },
    "ligand_tf_matrix_rownames.json": {
        "url": "https://zenodo.org/records/19549668/files/ligand_tf_matrix_rownames.json?download=1",
        "sha256": "970c93c1fedeb1298b0b287ac0a03d7eb792302218ed307c511d2f03928ccd4f",
    },
    "lr_network_human.parquet": {
        "url": "https://zenodo.org/records/19549668/files/lr_network_human.parquet?download=1",
        "sha256": "e26f9aa25e08bacb4a5ca620108c8bc0f0b50be6ba7388f176e596f3954ccadf",
    },
    "lr_network_mouse.parquet": {
        "url": "https://zenodo.org/records/19549668/files/lr_network_mouse.parquet?download=1",
        "sha256": "36882706897618e0619b41292c071c847b06c91d9cdfd1806074f08392346c50",
    },
    "pemt_signature.txt": {
        "url": "https://zenodo.org/records/19549668/files/pemt_signature.txt?download=1",
        "sha256": "ba4b0127498435fc5b7779191754a238625bd53463af367d96d948fcc64e4759",
    },
    "seuratObj.h5ad": {
        "url": "https://zenodo.org/records/19549668/files/seuratObj.h5ad?download=1",
        "sha256": "5d60271ec60d851d6239cc7400d1fed58d83560f7bfa0b85be228f0aa42be688",
    },
    "sig_network_human.parquet": {
        "url": "https://zenodo.org/records/19549668/files/sig_network_human.parquet?download=1",
        "sha256": "051610926004ed5b62bf5d9e3197c2c21e4f8659649e19e35f8ebfc76b164b38",
    },
    "weighted_networks_human_gr.parquet": {
        "url": "https://zenodo.org/records/19549668/files/weighted_networks_human_gr.parquet?download=1",
        "sha256": "33746f3ecc48584bf80023ec36881765f09a424c0bd8a252c10ed6122df3e15a",
    },
    "weighted_networks_human_lr_sig.parquet": {
        "url": "https://zenodo.org/records/19549668/files/weighted_networks_human_lr_sig.parquet?download=1",
        "sha256": "66c6945d730ec31f2f83c8fb73ae1af6725d45692994842a4b644b730d92a788",
    },
    "weighted_networks_mouse_gr.parquet": {
        "url": "https://zenodo.org/records/19549668/files/weighted_networks_mouse_gr.parquet?download=1",
        "sha256": "2001891ecc8cc54d826484a773241c6221646c47e8ba1753f9c75b9516d20055",
    },
    "weighted_networks_mouse_lr_sig.parquet": {
        "url": "https://zenodo.org/records/19549668/files/weighted_networks_mouse_lr_sig.parquet?download=1",
        "sha256": "16a802a52fc015b9f4c695a6cf5d75a018c33c86dace474962e8f33e16c44faa",
    },
}
